### ISSUE TITLE
SC4S_SOURCE_LISTEN_RFC6587_SOCKETS not working

### ISSUE THREAD

**Issue by chrisengie** [splunk/splunk-connect-for-syslog#1836]
I think I found a bug. In env_file, if I set:
`SC4S_SOURCE_LISTEN_RFC6587_SOCKETS=2
`The containers refuses to start and this is the error:
```
Traceback (most recent call last):
  File "/etc/syslog-ng/conf.d/sources/source_syslog/plugin.py", line 110, in <module>
    outputText = tm.render(
  File "/root/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/root/.local/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/etc/syslog-ng/conf.d/sources/source_syslog/plugin.jinja", line 316, in top-level template code
    {%- for i in range(1,port_6587_sockets+1) %}
TypeError: can only concatenate str (not "int") to str
[2022-09-30T10:06:06.795178] confgen: Generator program returned with non-zero exit code; reference='/etc/syslog-ng/conf.d/sources/source_syslog/plugin.conf:4:1', context='root', block='source_syslog', exec='/etc/syslog-ng/conf.d/sources/source_syslog/plugin.py', rc='256'
Error parsing config, syntax error, unexpected LL_ERROR, expecting end of file in /etc/syslog-ng/conf.d/sources/source_syslog/plugin.conf:4:1-4:14:

Included from /etc/syslog-ng/syslog-ng.conf:44:1-44:1:
39
40      @include "conf.d/plugin/*.conf"
41
42      @include "conf.d/sources/*.conf"
43      @include "conf.d/sources/*/*.conf"
44----> @include "conf.d/local/config/sources/*.conf"
44----> ^
45      @include "conf.d/local/config/sources/*/*.conf"
46
47      @include "conf.d/destinations/*.conf"
48      @include "conf.d/destinations/*/*.conf"
49


syslog-ng documentation: https://www.syslog-ng.com/technical-documents/list/syslog-ng-open-source-edition
contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
```
Other settings such as SC4S_SOURCE_LISTEN_RFC5426_SOCKETS & SC4S_SOURCE_LISTEN_RFC5425_SOCKETS work well.
I found these settings here: https://splunk.github.io/splunk-connect-for-syslog/main/configuration/#syslog-source-configuration

**Comment by rjha-splunk** [comment]
fixed in release 2.42.0
